apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster }}-{{ .Release.Name }}-namespaces
spec:
  project: default
  source:
    helm:
      releaseName: '{{ .Release.Name }}'
      valueFiles:
      - '../../teams/{{ .Values.prefix }}/{{ .Release.Name }}/values.yaml'
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: charts/namespaces
  destination:
    namespace: '*'
    name: {{ .Values.cluster }}
  syncPolicy:
    automated: {}